language: node_js

node_js:
  - 'stable'

before_script:
- rm -rf ./node_modules package-lock.json
- npm install

before_deploy:
  - npm test

deploy:
  provider: script
  script:
    - 'echo "TODO: deploy the app. Directory listing:" && ls -R dist'
  skip_cleanup: true
  on:
    branch: master